project_id = "tsnlbfjltskscgyidgdt"

[functions.analyze-collectible]
verify_jwt = false

[functions.fetch-listings]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.create-subscription]
verify_jwt = false

[functions.start-trial]
verify_jwt = false
